version: "3.8"

services:
  redis:
    image: redis:5
    command: redis-server --port 6379
    ports:
      - 6379:6379

  nginx:
    image: yubi5050/sidepro-nginx:latest
    ports:
      - 80:80
    depends_on:
      - web
      - asgiserver

  web:
    image: yubi5050/sidepro:latest
    command: bash -c "service cron start && python manage.py crontab add && gunicorn --workers=2 sidepro.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /sidepro_be/
    volumes:
      - ./:/sidepro_be/
    expose:
      - 8000

  asgiserver:
    image: yubi5050/sidepro:latest
    command: daphne -u /tmp/daphne.sock sidepro.asgi:application --bind 0.0.0.0 -p 8001
    ports:
      - 8001:8001
    working_dir: /sidepro_be/
    volumes:
      - ./:/sidepro_be/
    expose:
      - 8001
