version: "3.8"

services:
  redis:
    image: redis:5
    command: redis-server --port 6379
    ports:
      - 6379:6379

  nginx:
    build: ./nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - asgiserver

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  web:
    build: .
    command: bash -c "service cron start && python manage.py crontab add && gunicorn --workers=2 sidepro.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /sidepro_be/
    volumes:
      - ./:/sidepro_be/
    expose:
      - 8000
    env_file:
      - ./.env

  asgiserver:
    build: .
    command: daphne -u /tmp/daphne.sock sidepro.asgi:application --bind 0.0.0.0 -p 8001
    ports:
      - 8001:8001
    working_dir: /sidepro_be/
    volumes:
      - ./:/sidepro_be/
    env_file:
      - ./.env
    expose:
      - 8001
