name: BE-CI-CD

on:
  push:
    branches:
      - publish
jobs:
  build-web-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: create env file
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env
    
    # Docker build -env
    - name: Build and Push the Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./Dockerfile
        tags : ${{ secrets.DOCKERHUB_USERNAME }}/sidepro:lastest
        env_file: ./.env

  # nginx:
  #   runs-on: 
  #   - name: Build the Nginx image
  #     run: docker build . --file nginx/Dockerfile \
  #       --tag sidepro-be:$(date +%s)

  # cd-pipeline:
  #   needs: build-image
  #   name: continuos deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@publish
  #     - name: copy file via ssh password
  #       uses: appleboy/scp-action@master
  #       with:
  #         host: ${{ secrets.EC2_PRIVATE_HOST }}
  #         username: ubuntu
  #         key: ${{ secrets.EC2_PRIVATE_KEY }}
  #         source: "docker-compose.yml"
  #         target: "/home/ubuntu/"
  #     - name: executing remote ssh commands using password
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.EC2_PRIVATE_HOST }}
  #         username: ubuntu
  #         key: ${{ secrets.EC2_PRIVATE_KEY }}
  #         script: "docker-compose pull && docker-compose up -d"
