name: BE-CI-CD

on:
  push:
    branches:
      - development
jobs:
  # build web image
  build-web-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: create env file
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env
    
    # Docker build -env
    - name: Build and Push the Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./Dockerfile
        tags : ${{ secrets.DOCKERHUB_USERNAME }}/sidepro:latest
        env_file: ./.env

    # nginx:
    - name : Build Nginx image
      id: nginx_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./nginx/Dockerfile
        tags : ${{ secrets.DOCKERHUB_USERNAME }}/sidepro-nginx:latest
      
  # cd-pipeline
  cd-pipeline:
    needs: build-web-image
    name: continuos deploy
    runs-on: ubuntu-latest
    steps:
      # Send yaml, sh Files
      - uses: actions/checkout@v3
      - name: copy file via ssh password - .yaml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/"
      - name: copy file via ssh password - .sh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "config/deploy.sh"
          target: "/home/ubuntu/"
      
      # Install Docker, Docker-compose
      - name: docker, docker-compose install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script : "sh /home/ubuntu/config/deploy.sh"

      # Docker-compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: "sudo docker login -u ${{secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && sudo docker-compose down && sudo docker-compose pull && sudo docker-compose up -d "
